In [ ]:
#one dim array
#two dim array
#n-dimension array
#!pip install num py
#properties of num py array

In [5]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
x = [[1,2,3],[6,5,4]]
print(type(x))

<class 'list'>


In [3]:
x_arr = np.array(x)
x_arr

array([[1, 2, 3],
       [6, 5, 4]])

In [4]:
print(type(x_arr))

<class 'numpy.ndarray'>


In [8]:
x1 = [1,2,3]
x1_np = np.array(x1)
x1_np.shape

(3,)

In [6]:
#shape() will return in tupple format
x_arr.shape

(2, 3)

In [9]:
x3 = [[5,6,7,8],[8,9,6,4]]
x3_arr = np.array(x3)
x3_arr.shape

(2, 4)

In [10]:
x3_arr

array([[5, 6, 7, 8],
       [8, 9, 6, 4]])

In [11]:
x4 = [[4,8,9,6],[9,6,5,4],[7,6,9,5],[7,8,5,6]]
x4_arr = np.array(x4)
x4_arr.shape

(4, 4)

In [13]:
x4_arr.ndim
#n.dim means it gives dimention 

2

In [14]:
x4_arr.size

16

In [15]:
x3_arr.dtype

dtype('int64')

In [16]:
x33 = [[5,6,7,8],[8.6,9,6,4]]
x33_arr = np.array(x33)
x33_arr.shape

(2, 4)

In [17]:
x33_arr.dtype

dtype('float64')

In [20]:
a = [1,'s',7.9]
print(a)
a_arr = np.array(a)

[1, 's', 7.9]


In [21]:
a_arr.dtype

dtype('<U32')

In [22]:
print(x3_arr.mean())

6.625


In [29]:
median = np.median(x_arr)
print(median)

3.5


In [30]:
mean = np.mean(x_arr)
print(mean)

3.5


In [28]:
standard_dev = np.std(x_arr)
print(standard_dev)

1.707825127659933


In [31]:
add = np.sum(x_arr)
print(add)

21


In [32]:
maximum = np.max(x_arr)
print(maximum)

6


In [34]:
minimum = np.min(x_arr)
print(minimum)

1


In [35]:
x=[1,3]
x1 =[5,6]
print(x+x1)
#i list we cannot do mathematical operations

[1, 3, 5, 6]


In [38]:
x=[1,3]
x1 =[5,6]
x_arr = np.array(x)
x1_arr = np.array(x1)
print(x_arr+x1_arr)
#in num pi we can operate in mathematical operations

[6 9]


In [41]:
dat1 = [1,2,3]*2
print(dat1)

[1, 2, 3, 1, 2, 3]


In [46]:
dat1 = [1,2,3]
dat1_arr = np.array(dat1)
print(dat1_arr*2)

[2 4 6]


In [4]:
import numpy as np 
array = np.random.randint(0,10,size=5)
print(array)

[3 0 5 1 9]


In [14]:
x = [[1,2,3],[6,5,4]]
x_arr = np.array(x)
print(x_arr)
x_arr.shape


[[1 2 3]
 [6 5 4]]


(2, 3)

In [15]:
x = [[1,2,3],[6,5,4]]
x_arr = np.array(x)
print(x_arr)
x_arr_reshape = x_arr.reshape(3,2)    

[[1 2 3]
 [6 5 4]]


In [16]:
array_1 = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(array_1)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [17]:
 print(array_1[0])

[10 20 30 40]


In [18]:
print(array_1[0])

[10 20 30 40]


In [20]:
print(array_1[0:2])

[[10 20 30 40]
 [50 60 70 80]]


In [21]:
print(array_1[1:3])

[[ 50  60  70  80]
 [ 90 100 110 120]]


In [22]:
print(array_1[:,1:3])

[[ 20  30]
 [ 60  70]
 [100 110]]


In [23]:
print(array_1[:,0])

[10 50 90]


In [24]:
array_1[2] == array_1[-1]

array([ True,  True,  True,  True])

In [25]:
array_1[-1]

array([ 90, 100, 110, 120])

In [26]:
array_1[2]

array([ 90, 100, 110, 120])

In [27]:
5==9

False

In [31]:
print(array_1[1,3])

80


In [34]:
print(array_1[1,1:3])

[60 70]


In [8]:
import numpy as np
x1=[1,4,9,13,19]
x2 =[1000,1001,1002,1004]
x3 =[0.009,0.0008,0.2,0.05]
x1_arr = np.array(x1)
x2_arr = np.array(x2)
x3_arr = np.array(x3)
print(x1_arr.std())
print(x2_arr.std())
print(x3_arr.std())  #std =standard deviation

6.4
1.479019945774904
0.08016799548448246


In [10]:
#boolean means it has two values true & false
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [16]:
print(arr,[0])

[10 20 30 40 50] [0]


In [12]:
filtered = arr[arr>25]
filtered


array([30, 40, 50])

In [13]:
arr[2:]

array([30, 40, 50])

In [14]:
print(arr[arr>20])  #boolean indexing

[30 40 50]


In [17]:
filtered = [arr > 25]
filtered

[array([False, False,  True,  True,  True])]

In [23]:
file1 = np.loadtxt("malhar.txt",delimiter = ",")
file1   #to load dile directly 

array([[1.2, 3.4, 5.6],
       [3.4, 6. , 7.8]])

In [26]:
import numpy as np
linspace_array = np.linspace(0,1,5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
import numpy as np
a =[1,2,3,4,5]
a_arr = np.array(a)

a_arr1 = sum(a_arr)/len(a_arr)
a_arr1

np.float64(3.0)

In [16]:
a_arr1.mean()

np.float64(3.0)

In [17]:
import numpy as np
a = [1,2,3,4,5]
a_arr = np.array(a)


In [20]:
a = [1,2,3,4,5]
a_arr = np.array(a)
sum = 0
for i in a_arr:
    sum= sum+i
print(sum)
no_of_elements = 0
for i in a_arr:
    no_of_elements += 1
avg = sum/no_of_elements
print(avg)

15
3.0
